-- SQL script til oprettelse af tabeller til annotator
-- SQL autogenereret af SQLDeveloper 
-- NB! hardkoede referencer til bruger "luftfototest"


-- COMMENTS --
CREATE TABLE "LUFTFOTOTEST"."COMMENTS"
  (
    "COMMENT_TEXT" VARCHAR2(2048 BYTE),
    "CREATOR"      VARCHAR2(100 BYTE),
    "TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
    "XLINK_TO" VARCHAR2(200 BYTE),
    "ID"       VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "HOST_URI" VARCHAR2(220 BYTE),
    CONSTRAINT "GUID_CONSTRAINT" UNIQUE ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "LUFTFOTOTEST"."GUID_CONSTRAINT" ON "LUFTFOTOTEST"."COMMENTS"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
-- TAGS --  
  CREATE TABLE "LUFTFOTOTEST"."TAG"
  (
    "ID"        VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "TAG_VALUE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "CREATOR"   VARCHAR2(100 BYTE),
    "TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
    "XLINK_TO" VARCHAR2(200 BYTE),
    CONSTRAINT "TAG_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  
  -- XLINKS --
  CREATE TABLE "LUFTFOTOTEST"."XLINK"
  (
    "ID"         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "XLINK_FROM" VARCHAR2(200 BYTE) NOT NULL ENABLE,
    "XLINK_TO"   VARCHAR2(200 BYTE) NOT NULL ENABLE,
    "XLINK_TYPE" VARCHAR2(20 BYTE) DEFAULT 'simple' NOT NULL ENABLE,
    "XLINK_ROLE" VARCHAR2(100 BYTE),
    "CREATOR"    VARCHAR2(100 BYTE),
    "TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
    "XLINK_TITLE" VARCHAR2(200 BYTE),
    CONSTRAINT "XLINK_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "LUFTFOTOTEST"."XLINK_INDEX_CERATOR" ON "LUFTFOTOTEST"."XLINK"
  (
    "CREATOR"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "LUFTFOTOTEST"."XLINK_INDEX_FROM" ON "LUFTFOTOTEST"."XLINK"
  (
    "XLINK_FROM"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "LUFTFOTOTEST"."XLINK_INDEX_TO" ON "LUFTFOTOTEST"."XLINK"
  (
    "XLINK_TO"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE UNIQUE INDEX "LUFTFOTOTEST"."XLINK_PK" ON "LUFTFOTOTEST"."XLINK"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
